# EVO_FX_MASTER - Ana Konfigürasyon Dosyası
# ==========================================
# MASTER PROMPT gereksinimlerine göre hazırlanmıştır

# Proje Bilgileri
project:
  name: "EVO_FX_MASTER"
  version: "1.0.0"
  description: "NEAT tabanlı evrimsel forex trading sistemi"

# Veri Kaynakları
data_sources:
  # OANDA REST API (birincil kaynak)
  oanda:
    base_url: "https://api-fxpractice.oanda.com"  # Demo hesap
    # base_url: "https://api-fxtrade.oanda.com"   # Gerçek hesap
    token: ""  # Buraya OANDA token'ınızı girin
    account: ""  # Hesap ID'nizi girin
    
  # MT5 Fallback
  mt5:
    enabled: true
    login: ""     # MT5 hesap numarası
    password: ""  # MT5 şifresi  
    server: ""    # Broker sunucusu
    path: ""      # MT5 terminal yolu (opsiyonel)

# Trading Sembolleri
symbols:
  EURUSD:
    enabled: true
    weight: 0.6  # Fitness ağırlığı
    commission: 0.0002  # 2 pip komisyon
    slippage: 0.0001    # 1 pip slippage
    min_spread: 0.1     # pip
    max_spread: 3.0     # pip
    
  XAUUSD:
    enabled: true
    weight: 0.4
    commission: 0.00035  # 3.5 pip komisyon
    slippage: 0.0001     # 1 pip slippage
    min_spread: 0.2      # pip
    max_spread: 5.0      # pip

# Veri Parametreleri
data:
  timeframe: "M1"  # 1 dakika
  lookback_days: 365  # Kaç günlük veri
  train_ratio: 0.7     # %70 train, %30 test
  validation_ratio: 0.15  # %15 validation
  
  # Veri temizleme
  fill_method: "forward"
  outlier_threshold: 3.0  # Z-score
  min_bars: 100  # Minimum bar sayısı

# Feature Engineering
features:
  # Teknik indikatörler
  technical:
    rsi_period: 14
    atr_period: 14
    volatility_period: 30
    bollinger_period: 20
    bollinger_std: 2.0
    
    # Moving averages
    ma_short: 12
    ma_long: 26
    ma_signal: 9
    ma_periods: [5, 10, 12, 20, 26, 50, 100, 200]
    
    # MACD
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
  
  # Mikroyapısal özellikler
  microstructure:
    tick_momentum_periods: [5, 10, 20]
    volume_periods: [10, 20, 50]
    spread_periods: [10, 20]
    
  # Cross-asset korelasyon
  correlation:
    periods: [20, 50, 100]
    min_observations: 50

# NEAT Algoritması Parametreleri
neat:
  # Popülasyon
  population_size: 128
  max_generations: 400
  stagnation_generations: 20
  elitism_ratio: 0.1
  
  # Speciation
  speciation_threshold: 2.5
  target_species: 8
  survival_threshold: 0.3
  compatibility_weights: [1.0, 1.0, 0.4]  # c1, c2, c3
  
  # Mutasyon oranları
  mutation:
    add_node_prob: 0.03
    add_connection_prob: 0.05
    weight_mutate_prob: 0.8
    weight_replace_prob: 0.1
    bias_mutate_prob: 0.7
    disable_connection_prob: 0.01
    enable_connection_prob: 0.25
    
  # Mutasyon şiddetleri
  mutation_power:
    weight_mutate_power: 0.2
    bias_mutate_power: 0.1
    weight_init_range: [-1.0, 1.0]
  
  # Crossover
  crossover:
    crossover_prob: 0.75
    interspecies_mating_prob: 0.001
    
  # Fitness
  fitness:
    min_improvement: 0.001
    complexity_penalty: 0.0001
    
  # Parallellik
  num_workers: 7  # CPU count - 1

# Fitness Fonksiyonu
fitness:
  formula: "profit_per_trade × trade_count / (1 + max_drawdown_bars)"
  
  # Minimum gereksinimler
  min_trades: 10
  min_win_rate: 0.3
  max_drawdown: 0.5  # %50
  
  # Ağırlıklar (EURUSD: 0.6, XAUUSD: 0.4)
  symbol_weights:
    EURUSD: 0.6
    XAUUSD: 0.4

# Risk ve Para Yönetimi
risk:
  # Temel risk parametreleri
  base_risk_percent: 0.01     # %1 hesap riski
  max_risk_percent: 0.03      # %3 maksimum risk
  min_risk_percent: 0.005     # %0.5 minimum risk
  
  # Pozisyon boyutu
  max_position_percent: 0.2   # %20 maksimum pozisyon
  min_lot_size: 0.01
  max_lot_size: 10.0
  
  # ATR tabanlı stop-loss/take-profit
  atr_multiplier_sl: 1.1      # SL = ATR × 1.1
  atr_multiplier_tp: 2.2      # TP = ATR × 2.2
  min_rr_ratio: 1.5           # Minimum Risk:Reward
  
  # Günlük limitler
  daily_loss_limit: 0.04      # %4 günlük kayıp limiti
  daily_profit_target: 0.06   # %6 günlük kar hedefi
  max_trades_per_day: 20
  
  # Equity koruma
  equity_stop_percent: 0.15   # %15 equity kaybı → dur
  trailing_stop_percent: 0.05 # %5 trailing stop
  
  # Sinyal kuvvetine göre risk ayarlama
  signal_risk_multipliers:
    weak: 0.5     # 0-0.3 sinyal kuvveti
    medium: 1.0   # 0.3-0.6 sinyal kuvveti  
    strong: 1.5   # 0.6-0.8 sinyal kuvveti
    very_strong: 2.0  # 0.8+ sinyal kuvveti

# Live Trading
live_trading:
  # Sinyal parametreleri
  signal_threshold: 0.1        # Minimum sinyal kuvveti
  signal_cooldown_minutes: 5   # Sinyal arası bekleme
  max_positions: 4             # Maksimum eş zamanlı pozisyon
  
  # Trading sessions (UTC)
  sessions:
    sydney: [22, 6]    # 22:00-06:00 UTC
    tokyo: [0, 8]      # 00:00-08:00 UTC  
    london: [8, 16]    # 08:00-16:00 UTC
    newyork: [13, 21]  # 13:00-21:00 UTC
    
  # Session çarpanları (risk ayarlama)
  session_multipliers:
    sydney: 0.8
    tokyo: 0.9
    london: 1.2
    newyork: 1.1
    overlap_london_ny: 1.3

# Backtest ve Optimizasyon
backtest:
  # Grid search parametreleri
  grid_search:
    population_sizes: [64, 128]
    stagnation_generations: [15, 25]
    speciation_thresholds: [2.0, 3.0]
    n_runs_per_config: 3
    
  # Backtest parametreleri
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  initial_balance: 10000.0
  
  # Sonuç filtreleme
  min_fitness_threshold: 0.1
  top_n_results: 10
  
  # Parallellik
  max_workers: 7
  
  # Rapor
  create_notebook: true
  save_results: true

# Görselleştirme
visualization:
  # Stil
  style: "default"
  dpi: 100
  figsize: [15, 10]
  
  # Renkler
  colors:
    profit: "#00C851"      # Yeşil
    loss: "#FF4444"        # Kırmızı
    equity: "#2196F3"      # Mavi
    drawdown: "#FF9800"    # Turuncu
    network_pos: "#4CAF50" # Pozitif ağırlık
    network_neg: "#F44336" # Negatif ağırlık
    
  # Network diagram
  network:
    edge_threshold: 0.15   # Minimum ağırlık eşiği
    node_size: 120
    show_weights: true

# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Dosya logging
  file_logging: true
  log_dir: "logs"
  max_size_mb: 10
  backup_count: 5
  
  # Console logging
  console_logging: true

# Bildirimler (opsiyonel)
notifications:
  # Telegram
  telegram:
    enabled: false
    bot_token: ""
    chat_id: ""
    
  # E-posta
  email:
    enabled: false
    smtp_server: ""
    smtp_port: 587
    username: ""
    password: ""
    to_email: ""
    
  # Discord webhook
  discord:
    enabled: false
    webhook_url: ""

# Dosya Yolları
paths:
  data_dir: "data"
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  results_dir: "results"
  notebooks_dir: "notebooks"
  logs_dir: "logs"
  models_dir: "models"

# Performans
performance:
  # Pandas optimizasyonları
  pandas_optimize: true
  
  # Numpy thread sayısı
  numpy_threads: 4
  
  # Memory mapping
  use_memory_map: true
  
  # Garbage collection
  gc_frequency: 100  # Her 100 nesil

# Debugging
debug:
  enabled: false
  save_population: false
  save_fitness_details: false
  verbose_mutations: false
  plot_fitness_evolution: true